package ar.com.infocompany.entities;

// Generated May 5, 2010 12:03:02 AM by Hibernate Tools 3.2.4.GA

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private Integer CompanyId;
	private String Name;
	private Field CompanyField;

	public Company() {
	}

	public Company(Field CompanyField) {
		this.CompanyField = CompanyField;
	}

	public Company(String Name, Field CompanyField) {
		this.Name = Name;
		this.CompanyField = CompanyField;
	}

	public Integer getCompanyId() {
		return this.CompanyId;
	}

	public void setCompanyId(Integer CompanyId) {
		this.CompanyId = CompanyId;
	}

	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

	public Field getCompanyField() {
		return this.CompanyField;
	}

	public void setCompanyField(Field CompanyField) {
		this.CompanyField = CompanyField;
	}

}
