package ar.com.infocompany.entities;

// Generated May 5, 2010 12:03:02 AM by Hibernate Tools 3.2.4.GA

/**
 * Field generated by hbm2java
 */
public class Field implements java.io.Serializable {

	private Integer FieldId;
	private String Description;

	public Field() {
	}

	public Field(String Description) {
		this.Description = Description;
	}

	public Integer getFieldId() {
		return this.FieldId;
	}

	public void setFieldId(Integer FieldId) {
		this.FieldId = FieldId;
	}

	public String getDescription() {
		return this.Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}

}
