package ar.com.infocompany.entities;

// Generated May 5, 2010 12:03:02 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer UserId;
	private String UserName;
	private String Password;
	private String FirstName;
	private String LastName;
	private String Email;
	private Date CreationDate;

	public User() {
	}

	public User(String UserName, String Password, String FirstName,
			String LastName, String Email, Date CreationDate) {
		this.UserName = UserName;
		this.Password = Password;
		this.FirstName = FirstName;
		this.LastName = LastName;
		this.Email = Email;
		this.CreationDate = CreationDate;
	}

	public Integer getUserId() {
		return this.UserId;
	}

	public void setUserId(Integer UserId) {
		this.UserId = UserId;
	}

	public String getUserName() {
		return this.UserName;
	}

	public void setUserName(String UserName) {
		this.UserName = UserName;
	}

	public String getPassword() {
		return this.Password;
	}

	public void setPassword(String Password) {
		this.Password = Password;
	}

	public String getFirstName() {
		return this.FirstName;
	}

	public void setFirstName(String FirstName) {
		this.FirstName = FirstName;
	}

	public String getLastName() {
		return this.LastName;
	}

	public void setLastName(String LastName) {
		this.LastName = LastName;
	}

	public String getEmail() {
		return this.Email;
	}

	public void setEmail(String Email) {
		this.Email = Email;
	}

	public Date getCreationDate() {
		return this.CreationDate;
	}

	public void setCreationDate(Date CreationDate) {
		this.CreationDate = CreationDate;
	}

}
