// default package
// Generated Aug 6, 2010 3:10:54 AM by Hibernate Tools 3.2.4.GA

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer id;
	private Critic criticById;
	private Critic criticByCriticId;
	private User user;
	private String text;

	public Comment() {
	}

	public Comment(Critic criticById, Critic criticByCriticId, User user,
			String text) {
		this.criticById = criticById;
		this.criticByCriticId = criticByCriticId;
		this.user = user;
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Critic getCriticById() {
		return this.criticById;
	}

	public void setCriticById(Critic criticById) {
		this.criticById = criticById;
	}

	public Critic getCriticByCriticId() {
		return this.criticByCriticId;
	}

	public void setCriticByCriticId(Critic criticByCriticId) {
		this.criticByCriticId = criticByCriticId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
