// default package
// Generated Aug 6, 2010 3:10:54 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set critics = new HashSet(0);
	private Set critics_1 = new HashSet(0);

	public Company() {
	}

	public Company(String name) {
		this.name = name;
	}

	public Company(String name, Set critics, Set critics_1) {
		this.name = name;
		this.critics = critics;
		this.critics_1 = critics_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getCritics() {
		return this.critics;
	}

	public void setCritics(Set critics) {
		this.critics = critics;
	}

	public Set getCritics_1() {
		return this.critics_1;
	}

	public void setCritics_1(Set critics_1) {
		this.critics_1 = critics_1;
	}

}
