// default package
// Generated Aug 6, 2010 3:10:54 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Critic generated by hbm2java
 */
public class Critic implements java.io.Serializable {

	private Integer id;
	private User user;
	private Company company;
	private int salary;
	private Set commentsForCriticId = new HashSet(0);
	private Comment commentById;

	public Critic() {
	}

	public Critic(User user, Company company, int salary) {
		this.user = user;
		this.company = company;
		this.salary = salary;
	}

	public Critic(User user, Company company, int salary,
			Set commentsForCriticId, Comment commentById) {
		this.user = user;
		this.company = company;
		this.salary = salary;
		this.commentsForCriticId = commentsForCriticId;
		this.commentById = commentById;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public int getSalary() {
		return this.salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

	public Set getCommentsForCriticId() {
		return this.commentsForCriticId;
	}

	public void setCommentsForCriticId(Set commentsForCriticId) {
		this.commentsForCriticId = commentsForCriticId;
	}

	public Comment getCommentById() {
		return this.commentById;
	}

	public void setCommentById(Comment commentById) {
		this.commentById = commentById;
	}

}
